### ISSUE TITLE
Docs: Highlighting issue when using dark mode

### ISSUE THREAD

**Issue by sven-ahrens** [lhapaipai/symfony-vite-dev#12]
HTML ``<code></code>`` elements have the wrong background-color which makes them very hard or almost impossible to read.

![Bildschirmfoto 2024-01-17 um 10 02 00](https://github.com/lhapaipai/symfony-vite-dev/assets/18313443/06a14539-08ca-439f-9a96-b22aa8bb8086)

Here is the code that gets applied:

<img width="263" alt="Bildschirmfoto 2024-01-17 um 10 05 12" src="https://github.com/lhapaipai/symfony-vite-dev/assets/18313443/acbcc62a-c964-4b36-924a-bd0c3ddbdabf">

The background color is: ``#f8f8f8``

I'm not familiar with Vitepress but I think something like this should do the trick:

```
.dark {
  code {
    background-color: transparent;
    color: white;
  }
}
```

I tested this in Firefox & Chrome.

**Comment by lhapaipai** [comment]
Thanks for your feedback @sven-ahrens,
I also took the opportunity to remove the white background of the mermaid graphs, it's not perfect but it's not as bad :-)...
