### ISSUE TITLE
Crossorigin attribute needs adding to Link headers

### ISSUE THREAD

**Issue by andyexeter** [lhapaipai/symfony-vite-dev#15]
By default, this bundle adds a `type=module` attribute to regular JS scripts in EntrypointRenderer:

https://github.com/lhapaipai/symfony-vite-dev/blob/aa979ef086325f650da975832abc4a4bb0a62844/src/vite-bundle/src/Service/EntrypointRenderer.php#L170-L173

However, when using the `preload: 'link-header'` configuration the bundle does not add any `crossorigin` attribute to the Link header in PreloadAssetsEventListener:

https://github.com/lhapaipai/symfony-vite-dev/blob/aa979ef086325f650da975832abc4a4bb0a62844/src/vite-bundle/src/EventListener/PreloadAssetsEventListener.php#L39

As [module scripts require CORS protocol](https://html.spec.whatwg.org/multipage/scripting.html#the-script-element), this is causing the scripts to be loaded twice and the following warning in Chrome:

```
A preload for 'https://example.org/build/example.js' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.
```

I have implemented a quick fix in my local environment by adding the `crossorigin` attribute to all scripts in the Link header with:

```php
$link = $this->createLink('preload', $href)->withAttribute('as', 'script')->withAttribute('crossorigin', true);
```

I'm happy to submit a PR for this, but I'm wondering whether it needs to be more substantial.  Given that the default `type=module` attribute can be overridden in the call to `vite_entry_script_tags()` we might need to store the script `type` as well as `filePath` in the `getRenderedScripts()` so we can conditionally add the `crossorigin` attribute if the `type` is `module`. What do you think?

**Comment by lhapaipai** [comment]
Hi @andyexeter,
thank you for your message and your PR and sorry for my late answer... However I still wonder about the implementation. for all script and link tags, the `crossorigin` attribute can be omitted, set with empty string (or with `anonymous` string) but can alse take the `use-credentials` value.

I also looked at the implementation of webpack encore bundle and I find it rather interesting...

https://github.com/symfony/webpack-encore-bundle/blob/2.x/src/EventListener/PreLoadAssetsEventListener.php#L53

they actually added a bundle configuration option : `crossorigin`.
https://github.com/symfony/webpack-encore-bundle/blob/2.x/src/DependencyInjection/Configuration.php

What do you think about that ?
thank you again for your valuable response

**Comment by andyexeter** [comment]
Hi @lhapaipai,

Yes maybe we should add a bundle configuration option.

However the difference with this bundle and the webpack encore bundle is that this bundle adds the `type="module"` attribute to the script tags by default (required for Vite) which makes the request a CORS enabled request. 

This means that the `crossorigin` attribute _must_ be present on the Link header for the script to make it also a CORS enabled request for preloading to work. So in this part of the PR: 

```php
if ('module' === $tag->getAttribute('type')) {
    $link = $link->withAttribute('crossorigin', true);
}
```

We could swap out `true` for the bundle configuration option value, but we'd have to ignore the bundle configuration option value if it was `false`, otherwise preloading wouldn't work. Does this make sense?

**Comment by lhapaipai** [comment]
hi @andyexeter,
totally agree with you

I would add that yes it is possible to overwrite the `type="module"` attribute but in this case vite no longer works (this is a prerequisite for vite) so the developer must agree on the fact that **the `type="module"` attribute must be present in dev mode and after build**.

- a clarification when we compile our code with the legacy plugin.
this write content like this:
```html
<script type="module">try{import.meta.url;import("_").catch(()=>1);}catch(e){}window.__vite_is_modern_browser=true;</script>
<script type="module">
  (function() {
      if (window.__vite_is_modern_browser) return;
      console.warn("vite: loading legacy build because dynamic import or import.meta.url is unsupported, syntax error above should be ignored");
      var legacyPolyfill = document.getElementById("vite-legacy-polyfill")
      var script = document.createElement("script");
      script.src = legacyPolyfill.src;
      script.onload = function() {
          document.querySelectorAll("script.vite-legacy-entry").forEach(function(elt) {
              System.import(elt.getAttribute("data-src"));
          });
      };
      document.body.appendChild(script);
  })();
</script>
<script nomodule>!function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",(function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()}),!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();</script>
<script nomodule crossorigin src="/build/assets/polyfills-legacy-im0EAdDu.js" id="vite-legacy-polyfill"></script>
<script type="module" src="/build/assets/pageWelcome--4K79RzD.js"></script>
<script nomodule data-src="/build/assets/pageWelcome-legacy-TXGWt7m6.js" id="vite-legacy-entry-page-welcome" crossorigin class="vite-legacy-entry">System.import(document.getElementById("vite-legacy-entry-page-welcome").getAttribute("data-src"))</script>

```

we also find our `type="module"` attributes which are read by recent browsers and other script tags with the `nomodule` attributes for old browsers.
In this case also the developer must not globally change the `type="module"` attribute otherwise it will no longer work.

so this simplifies our work.

1. we can add a `crossorigin` option with only `"anonymous" | "use-credentials" | true` accepted values. maybe put a little explanation of why this attribute cannot be false
-> hum... we have already a crossorigin option !!! so just edit to disable false case.

2. report this choice in the PreloadAssetsEventListener.php

what do you think ?
