### ISSUE TITLE
Controllers are not loaded

### ISSUE THREAD

**Issue by matfire** [lhapaipai/symfony-vite-dev#43]
### vite-plugin-symfony version

7.0.4

### vite-bundle version

7.0.4

### your OS, node version, Symfony version, PHP version

OS Linux, node 21.7, Symfony 7 

### Description

It looks like the plugin is not able to detect the available controllers. Trying to use them both with the twig tag and directly writing the data-controller attribute yelds the same result.

vite.config.js:
```js
import { defineConfig } from "vite";
import symfonyPlugin from "vite-plugin-symfony";

/* if you're using React */
// import react from '@vitejs/plugin-react';

export default defineConfig({
    plugins: [
        /* react(), // if you're using React */
        symfonyPlugin({
            stimulus: true,
        }),
    ],
    build: {
        rollupOptions: {
            input: {
                app: "./assets/app.js",
            },
        }
    },
});
```

bootstrap.js:
```js
import { startStimulusApp, registerControllers } from "vite-plugin-symfony/stimulus/helpers";

const app = startStimulusApp();
registerControllers(
    app,
    import.meta.glob('./controllers/*_controller.js', {
        query: "?stimulus",
        /**
         * always true, the `lazy` behavior is managed internally with
         * import.meta.stimulusFetch (see reference)
         */
        eager: true,
    })
)
```

### How to reproduce

- start a new project
- install symfony-vite following the documentation
- add a `{{stimulus_controller}}` twig tag with a controller present in assets/controllers

**Comment by matfire** [comment]
```
assets
├── app.css
├── app.js
├── bootstrap.js
├── controllers
│   ├── courses_controller.js
│   ├── delay_controller.js
│   ├── graph_controller.js
│   ├── hello_controller.js
│   ├── map_controller.js
│   ├── mapDemo_controller.js
│   └── ol_controller.js
├── controllers.json
├── icons
│   ├── pajamas
│   │   └── hamburger.svg
│   └── symfony.svg
├── map.js
└── styles
    └── app.css


```

**Comment by lhapaipai** [comment]
seems correct...

have you added bootstrap.js in your app.js ?
```js
import "./bootstrap.js";
```

and `vite_entry_script_tags('app')` , `vite_entry_link_tags('app')` in your twig template ?

**Comment by lhapaipai** [comment]
what does you browser dev tool say about `#registerControllers` ?
![stimulus](https://github.com/user-attachments/assets/60ca2386-7e8e-4e60-b647-1550862ef9dd)

**Comment by matfire** [comment]
yes to all

**Comment by lhapaipai** [comment]
can you compare the real identier of your registeredController in the browser dev tool with the identifier in the `data-controller` attribute of your generated html.

**Comment by lhapaipai** [comment]
and can you take a screenshot of your dev tool and an extract of your html

**Comment by matfire** [comment]
I was about to answer that no controllers are loaded, but in the meantime I restarted my dev server and now everything loads properly
:clown_face: 
Sorry for creating a second issue for a problem that solved itself, again.

Thank you for your time!

**Comment by lhapaipai** [comment]
No problem.
have a good day
