### ISSUE TITLE
symfony/ux-vue type VueModule not exported

### ISSUE THREAD

**Issue by Supportic** [lhapaipai/symfony-vite-dev#50]
### vite-plugin-symfony version

6.5.3

### vite-bundle version

v6.5.3

### your OS, node version, Symfony version, PHP version

Ubuntu 22.04, Node 20.17, Symfony 6.4, PHP 8.3

### Description

The documentation imports VueModule twice (assets/bootstrap.ts) : https://symfony-vite.pentatrion.com/stimulus/symfony-ux.html#symfony-ux-vue

and VueModule does not get exported from 'vite-plugin-symfony/stimulus/helpers/vue'.

### How to reproduce

setup bootstrap.ts

### Possible Solution

Export type VueModule from 'vite-plugin-symfony/stimulus/helpers/vue'

or define locally in bootstrap.ts

```ts
import { Component } from 'vue';
type VueModule = {
  default: Component;
};
```

**Comment by lhapaipai** [comment]
Hi @Supportic,
thanks for your message,
I've removed the double import in the doc.

on the other hand I don't understand when you say that the `VueModule` type is not exported when you do:
```ts
import { VueModule } from 'vite-plugin-symfony/stimulus/helpers/vue'
```

can you copy-paste the content of your `node_modules/vite-plugin-symfony/dist/stimulus/helpers/vue/index.d.ts` or equivalent (depending on your package manager)

**Comment by Supportic** [comment]
Oh nevermind now it's there. Maybe it was there because of an older version. I updated to the latest recently.
I will close the issue.
